# 퍼셉트론 
- 퍼셉트론 : 최초 인공세포
- 단층 / 다층 -> 다층 : 할수 있는 일을 다양하게 만들수있다
- 멀티 레이어 퍼셉트론(다층) -> 시그모이드가 들어간 여러 일을 처리할 수 있는 (a달린) -> 뉴런 네트워크
- 편향 : 
- 일반적인 퍼셉트론 : 임계값 $\theta $을 넘으면 1, 넘지 못하면 0 -> $W_1X_1 - \theta <= 0 $
- 퍼셉트론의 계단함수 or 활성화 함수 : $U(z) = W_1X_1 - \theta $ 값은 0 or 1 
- $\theta = -b$로 치환하면 $y = W_1X_1 + W_2X_2 + b $

# 활성화 함수
- 인공 신경망을 다양하게 표현하기 위한 
- sigmoid : 신호의 세기. 0에 가까울 수록 작고, 1에 가까울 수록 강함.  중앙값은 쓸모없는 값
- tahn (Hyperblic Tangent) : 데이터의 방향성. 유사도. 1에 가까울수록 유사한 데이터, -1은 반대 데이터
- relu : 음수 또는 불필요한 데이터는 0, 양수나 사용할 데이터는 그대로, 이미지 분류에 사용.
- softmax (identity function-회귀문제): 일부데이터(k) / 전체데이터 --> softmax의 합은 무조건 1 -->  확률.


# 행렬 내적
- 행렬 내적 시 $A\cdot B$이면 모양이(x, y), (z, o)이면 y와 z의 값은 같아야한다
- 교환 법칙은 성립하지 않음

# 행렬과 신경망

입력층 ($x_1, x_2, x_3$), 은닉층(1층) 2개

$W^{to_1}_{(to_2)(from_3)}$ = 1 : ~번째 은닉층의 / 2 : 뉴런으로 가는, 3 : 가중치

input -> 은닉층
x = (x_1, x_2, x_3),  (1, 3) or (3,)
w = $\begin{bmatrix}
w^{(1)}_{11}& w^{(1)}_{12}\\
w^{(1)}_{12} &w^{(1)}_{22}\\
w^{(1)}_{13} &w^{(1)}_{23}
\end{bmatrix}$

$B = \begin{bmatrix}b^{(1)}_1 & b^{(1)}_2\end{bmatrix}$

A= a(z) (시그모이드 , relu, tanh...)
$A^{(1)}$ = (a_1, a_2) 
활성화 함수 개수 = 마지막 뉴런의 개수

활성화 함수는 일반적으로 한층 모두 동일하게 사용한다. 각 출력 뉴런마다 역할이 있기 때문에.



- 하이퍼 파라미터




- 모델 파라미터

- axis = 방향
- [1, 2, 3] -> max axis = 0
- axis = n -> arr 자체에 데이터가 추가되는 방향
- arr = [[1,2,3],[4,5,6]] 일떄 arr = 0이면 [4,5,6]아래에 [4,5,6] 형식으로 구성



In [2]:
import numpy as np

In [34]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [35]:
arr.max(axis=0) # 1차원 행렬에서, 가장 마지막 원소의 값을 도출. 이 방향으로 데이터가 추가 될 예정

5

In [30]:
arr = np.arange(6).reshape(2,3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [31]:
arr.max(axis=0) # 2차원 행렬에서, 가장 첫차원인 1차원 행렬의 값을 도출. 이 방향으로 데이터가 추가 될 예정

array([3, 4, 5])

In [33]:
arr.max(axis=1) # 2차원 행렬에서, 각 1차원의 가장 마지막 원소의 값을 도출. 이 방향으로 데이터가 추가 될 예정

array([2, 5])

In [37]:
arr = np.arange(12).reshape(2,3,2) #
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [38]:
arr.max(axis=0)  # 3차원 행렬에서, 가장 첫차원인 2차원의 행렬의 값을 도출. 이 방향으로 데이터가 추가 될 예정

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [39]:
arr.max(axis=1) # 3차원 행렬에서, 각 2차원의 원소 중 가장 마지막 1차원의 행렬 값을 도출.  이 방향으로 데이터가 추가 될 예정

array([[ 4,  5],
       [10, 11]])

In [41]:
arr.max(axis=2)  # 3차원 행렬에서, 각 2차원의 원소의 각 1차원의 가장 마지막 1차원의 행렬 값을 도출.  이 방향으로 데이터가 추가 될 예정

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [44]:
arr = np.arange(48).reshape(4,3,2,2) #
arr

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]],


       [[[24, 25],
         [26, 27]],

        [[28, 29],
         [30, 31]],

        [[32, 33],
         [34, 35]]],


       [[[36, 37],
         [38, 39]],

        [[40, 41],
         [42, 43]],

        [[44, 45],
         [46, 47]]]])

In [46]:
arr.max(axis=0)# [[[36, 37], [38, 39]], [[40, 41], [42, 43]], [[44, 45], [46, 47]]] #

array([[[36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43]],

       [[44, 45],
        [46, 47]]])

In [47]:
arr.max(axis=1)#

array([[[ 8,  9],
        [10, 11]],

       [[20, 21],
        [22, 23]],

       [[32, 33],
        [34, 35]],

       [[44, 45],
        [46, 47]]])

In [48]:
arr.max(axis=2)

array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]],

       [[26, 27],
        [30, 31],
        [34, 35]],

       [[38, 39],
        [42, 43],
        [46, 47]]])

In [49]:
arr.max(axis=3)

array([[[ 1,  3],
        [ 5,  7],
        [ 9, 11]],

       [[13, 15],
        [17, 19],
        [21, 23]],

       [[25, 27],
        [29, 31],
        [33, 35]],

       [[37, 39],
        [41, 43],
        [45, 47]]])

- softmax : 지수 함수로, 크기가 너무 커지는 것을 막고자, log함수 log(C)를 더함. 이는 함수로 -c로 사용한다.
- softmax 함수는 단조함수, 즉, 정의역 원소 a,b의 값의 크기가 a<b일 때, 함수 값도 f(a) < f(b)이다. 입력 값의 크기 순에 따라 출력 값 크기 순서도 동일하게 나온다. -> 예측에는 사용되지 않고, 그 값이 나올 확률만 알 수 있다.

- 배치 : 1장씩 또는 10장씩 나누는 단위
- 애폭 : 전체 1회 도는 횟수
- 미니배치 : ~개 중에 ~개를 랜덤으로 뽑아내는것. -> SGD

- 학습 : 가중치와 bias의 최적값을 찾기 위함이며 '미분'이라는 도구를 사용

- 머신러닝 전 : 사람이 알고리즘을 생각해서 컴퓨터는 결과만.
- 머신러닝 후 : 사람이 데이터에 대한 특징을 생각해내고, 머신러닝(SVM, KNN등)이 결과를 내었다.
- 레이블링 없이 하면 대표적인 비지도 학습

## loss 
- loss는 손실. 그렇기 떄문에 못했다를 현재의 상태, '지표' 로 둔다. 
- 잘됐다를 지표로 두면, 100%인 목표를 따라 편향될 수 있고, loss를 지표로 두면, 0에 가까운 여러 값을 나타낼 수 있다.
- 그리고 수학적으로 loss 함수를 미분하는 것이 cost 함수로 값을 구하는 것 보다 더 좋다.
- MSE : 공부용. 1/2 또한 이차함수라고 가정하는 MSE를 미분 했을 때, 곱해지는 값을 없애기 위해. 공부하기 쉽기 위해.
- 실제 사용: cross entropy 크로스 엔트로피. :  MSE보다 오차를 더 확실하게 인지 할 수 있다. 0을 내려가지 않는 로그 그래프
- 오차가 크면 loss가 크다. 

## 경사하강법을 위한 미분
- 속도에서의 미분 : 한 순간의 변화량
- 함수에서의 미분 : 기울기. y값의 변화량 / x값의 변화량 = $\frac {f(x+\Delta x) - f(x)}{x + \Delta x - x}$.
- $\Delta x$ 값을 최소한으로 줄이기 위해 limit로 $\Delta$ x를 0에 수렴하게 한다
- 분모의 값이 너무 작을 경우 0에 수렴하게 된다. 분모는 0이면 안되기 때문에 정방차분과 중앙차분을 이용해서,
  x를 기준으로 $x + \Delta x$ 와  $(x - \Delta x)$를 나누어, 이 값을 정의역으로 하여 기울기를 구한다.
- 이는 기울기는 동일하며 평행이동으로 이동할 수 있다는 것을 가정하기 때문에 문제가 없다.

## 편미분
- 특정 x값에 대한 미분을 구한다, 즉 $x_0$의 편미분을 구한다면 $x_1$을 무시하고 구하겠다.
    - 삭제하겠다는 것이 아닌 $x_1$ = 3일때의 $x_2$ = 3일 때 미분 값
    - 가중치를 구할 때 1번 가중치에 대한 loss율, 2번 가중치에 대한 loss율을 각각 구해야 하기 때문에 $W_1X_1$의 기울기 값을 구할 때는 $W_2X_2$를 무시하고, 반대의 경우도 동일하게 실행한다

##
- smapl_weight.pkl
    - MNIST 손글씨 데이터 셋을 분류하기 위한 가중치, 편향이 학습되어 있는 상태
    - MNIST 손글씨 데이터셋
       - 세로 28px, 가로 28px
       - 784 (28 * 28) 개의 입력값이 있다.
    - 은닉층 2개 층이 존재한다.
        - 1층 은닉층(W1) : (784, 50)
        - 2층 은닉층(W2) : (50, 100)
        
    - 숫자 10개를 분류 해야하기 때문에 출력층의 유닛은 10개

In [1]:
import numpy as np